

#define DEFINE_STRUCT_BIGINT_STRUCT(NAME, N)
#define DEFINE_STRUCT_BIGINT_ADD(NAME, N)
#define DEFINE_STRUCT_BIGINT_SUB(NAME, N)
#define DEFINE_STRUCT_BIGINT_MUL(NAME, N)
#define DEFINE_STRUCT_BIGINT_DIV(NAME, N)
#define DEFINE_STRUCT_BIGINT_MOD(NAME, N)
#define DEFINE_STRUCT_BIGINT(NAME, N)
