#include "common.h"

#define DEFINE_STRUCT_MAGMA(NAME, T)
#define DEFINE_STRUCT_QUASIGROUP(NAME, T)
#define DEFINE_STRUCT_LOOP(NAME, T)
#define DEFINE_STRUCT_SEMIGROUP(NAME, T)
#define DEFINE_STRUCT_MONOID(NAME, T)
#define DEFINE_STRUCT_GROUP(NAME, T)
#define DEFINE_STRUCT_RING(NAME, T)
#define DEFINE_STRUCT_FIELD(NAME, T)
