/**
 * (c) Ivan Janevski
 *
 * Matrix
 */

#include "common.h"

// typedef
#define DEFINE_STRUCT_MATRIX_TYPEDEF(NAME, T) \
    typedef struct NAME NAME##_t;

// struct
#define DEFINE_STRUCT_MATRIX_STRUCT(NAME, T) \
    struct NAME { \
        T* m_data; \
        int m_width; \
        int m_height; \
        STRUCT_MUTEX(b_mutex); \
    };


#define DEFINE_STRUCT_MATRIX(NAME, T) \
    DEFINE_STRUCT_MATRIX_TYPEDEF(NAME, T) \
    DEFINE_STRUCT_MATRIX_STRUCT(NAME, T) \
    DEFINE_STRUCT_MATRIX_ALLOC(NAME, T) \
    DEFINE_STRUCT_MATRIX_INIT(NAME, T) \
    DEFINE_STRUCT_MATRIX_DESTROY(NAME, T) \
    DEFINE_STRUCT_MATRIX_WIDTH(NAME, T) \
    DEFINE_STRUCT_MATRIX_HEIGHT(NAME, T) \
    DEFINE_STRUCT_MATRIX_CLONE(NAME, T) \
    \
    DEFINE_STRUCT_MATRIX_SET_MATRIX(NAME, T) \
    DEFINE_STRUCT_MATRIX_ADD_MATRIX(NAME, T) \
    DEFINE_STRUCT_MATRIX_MUL_MATRIX(NAME, T) \
    \
    DEFINE_STRUCT_MATRIX_SET(NAME, T) \
    DEFINE_STRUCT_MATRIX_ROW_SET(NAME, T) \
    DEFINE_STRUCT_MATRIX_COL_SET(NAME, T) \
    DEFINE_STRUCT_MATRIX_MAIN_DIAG_SET(NAME, T) \
    DEFINE_STRUCT_MATRIX_ANTI_DIAG_SET(NAME, T) \
    DEFINE_STRUCT_MATRIX_FULL_SET(NAME, T) \
    \
    DEFINE_STRUCT_MATRIX_ADD(NAME, T) \
    DEFINE_STRUCT_MATRIX_ROW_ADD(NAME, T) \
    DEFINE_STRUCT_MATRIX_COL_ADD(NAME, T) \
    DEFINE_STRUCT_MATRIX_MAIN_DIAG_ADD(NAME, T) \
    DEFINE_STRUCT_MATRIX_ANTI_DIAG_ADD(NAME, T) \
    DEFINE_STRUCT_MATRIX_FULL_ADD(NAME, T) \
    \
    DEFINE_STRUCT_MATRIX_MUL(NAME, T) \
    DEFINE_STRUCT_MATRIX_ROW_MUL(NAME, T) \
    DEFINE_STRUCT_MATRIX_COL_MUL(NAME, T) \
    DEFINE_STRUCT_MATRIX_MAIN_DIAG_MUL(NAME, T) \
    DEFINE_STRUCT_MATRIX_ANTI_DIAG_MUL(NAME, T) \
    DEFINE_STRUCT_MATRIX_FULL_MUL(NAME, T) \
    \












