/**
 * (c) Ivan Janevski
 *
 * Matrix
 */

#include "common.h"

// typedef
#define DEFINE_STRUCT_MATRIX_TYPEDEF(NAME, T) \
    typedef struct NAME NAME##_t;

// struct
#define DEFINE_STRUCT_MATRIX_STRUCT(NAME, T) \
    struct NAME { \
        T* m_data; \
        int m_width; \
        int m_height; \
        STRUCT_MUTEX(b_mutex); \
    };


#define DEFINE_STRUCT_MATRIX(NAME, T) \
    DEFINE_STRUCT_MATRIX_TYPEDEF(NAME, T) \
    DEFINE_STRUCT_MATRIX_STRUCT(NAME, T) \
    DEFINE_STRUCT_MATRIX_ALLOC(NAME, T) \
    DEFINE_STRUCT_MATRIX_INIT(NAME, T) \
    DEFINE_STRUCT_MATRIX_DESTROY(NAME, T) \
    DEFINE_STRUCT_MATRIX_WIDTH(NAME, T) \
    DEFINE_STRUCT_MATRIX_HEIGHT(NAME, T) \
    DEFINE_STRUCT_MATRIX_CLONE(NAME, T) \
    DEFINE_STRUCT_MATRIX_SUBMATRIX(NAME, T) \
    \
    DEFINE_STRUCT_MATRIX_IS_DIAGONAL(NAME, T) \
    DEFINE_STRUCT_MATRIX_IS_TRIANGULAR(NAME, T) \
    DEFINE_STRUCT_MATRIX_IS_UPPER_TRIANGULAR(NAME, T) \
    DEFINE_STRUCT_MATRIX_IS_LOWER_TRIANGULAR(NAME, T) \
    DEFINE_STRUCT_MATRIX_IS_EQUAL(NAME, T) \
    DEFINE_STRUCT_MATRIX_IS_VECTOR(NAME, T) \
    DEFINE_STRUCT_MATRIX_IS_ROW_VECTOR(NAME, T) \
    DEFINE_STRUCT_MATRIX_IS_COL_VECTOR(NAME, T) \
    \
    DEFINE_STRUCT_MATRIX_FILL(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_IDENTITY(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_ZERO_MATRIX(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_SCALING(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_TRANSLATION(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_ROTATION(NAME, T) \
    \
    DEFINE_STRUCT_MATRIX_SET_MATRIX(NAME, T) \
    DEFINE_STRUCT_MATRIX_ADD_MATRIX(NAME, T) \
    DEFINE_STRUCT_MATRIX_MUL_MATRIX(NAME, T) \
    DEFINE_STRUCT_MATRIX_TRANSPOSE(NAME, T) \
    DEFINE_STRUCT_MATRIX_ADJUGATE(NAME, T) \
    DEFINE_STRUCT_MATRIX_INVERSE(NAME, T) \
    DEFINE_STRUCT_MATRIX_CONJUGATE(NAME, T) \
    DEFINE_STRUCT_MATRIX_TRACE(NAME, T) \
    \
    DEFINE_STRUCT_MATRIX_APPEND_ROW(NAME, T) \
    DEFINE_STRUCT_MATRIX_APPEND_COL(NAME, T) \
    DEFINE_STRUCT_MATRIX_INSERT_ROW(NAME, T) \
    DEFINE_STRUCT_MATRIX_INSERT_COL(NAME, T) \
    DEFINE_STRUCT_MATRIX_DELETE_ROW(NAME, T) \
    DEFINE_STRUCT_MATRIX_DELETE_COL(NAME, T) \
    DEFINE_STRUCT_MATRIX_ROW_SWAP(NAME, T) \
    DEFINE_STRUCT_MATRIX_COL_SWAP(NAME, T) \
    \
    DEFINE_STRUCT_MATRIX_SET(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_ROW(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_COL(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_DIAG(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_MAIN_DIAG(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_ANTI_DIAG(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_TRIANGLE(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_UPPER_TRIANGLE(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_LOWER_TRIANGLE(NAME, T) \
    DEFINE_STRUCT_MATRIX_SET_ALL(NAME, T) \
    DEFINE_STRUCT_MATRIX_ROW_SET_ROW(NAME, T)\
    DEFINE_STRUCT_MATRIX_COL_SET_COL(NAME, T)\
    \
    DEFINE_STRUCT_MATRIX_ADD(NAME, T) \
    DEFINE_STRUCT_MATRIX_ADD_ROW(NAME, T) \
    DEFINE_STRUCT_MATRIX_ADD_COL(NAME, T) \
    DEFINE_STRUCT_MATRIX_ADD_DIAG(NAME, T) \
    DEFINE_STRUCT_MATRIX_ADD_MAIN_DIAG(NAME, T) \
    DEFINE_STRUCT_MATRIX_ADD_ANTI_DIAG(NAME, T) \
    DEFINE_STRUCT_MATRIX_ADD_TRIANGLE(NAME, T) \
    DEFINE_STRUCT_MATRIX_ADD_UPPER_TRIANGLE(NAME, T) \
    DEFINE_STRUCT_MATRIX_ADD_LOWER_TRIANGLE(NAME, T) \
    DEFINE_STRUCT_MATRIX_ADD_ALL(NAME, T) \
    DEFINE_STRUCT_MATRIX_ROW_ADD_ROW(NAME, T)\
    DEFINE_STRUCT_MATRIX_COL_ADD_COL(NAME, T)\
    \
    DEFINE_STRUCT_MATRIX_MUL(NAME, T) \
    DEFINE_STRUCT_MATRIX_MUL_ROW(NAME, T) \
    DEFINE_STRUCT_MATRIX_MUL_COL(NAME, T) \
    DEFINE_STRUCT_MATRIX_MUL_DIAG(NAME, T) \
    DEFINE_STRUCT_MATRIX_MUL_MAIN_DIAG(NAME, T) \
    DEFINE_STRUCT_MATRIX_MUL_ANTI_DIAG(NAME, T) \
    DEFINE_STRUCT_MATRIX_MUL_TRIANGLE(NAME, T) \
    DEFINE_STRUCT_MATRIX_MUL_UPPER_TRIANGLE(NAME, T) \
    DEFINE_STRUCT_MATRIX_MUL_LOWER_TRIANGLE(NAME, T) \
    DEFINE_STRUCT_MATRIX_MUL_ALL(NAME, T) \
    DEFINE_STRUCT_MATRIX_ROW_MUL_ROW(NAME, T)\
    DEFINE_STRUCT_MATRIX_COL_MUL_COL(NAME, T)\
    \
    DEFINE_STRUCT_MATRIX_DETERMINANT(NAME, T) \
    DEFINE_STRUCT_MATRIX_COFACTOR(NAME, T) \
    DEFINE_STRUCT_MATRIX_GAUSS(NAME, T) \
    DEFINE_STRUCT_MATRIX_LU(NAME, T) \
    \
    DEFINE_STRUCT_MATRIX_EXP(NAME, T) \
    DEFINE_STRUCT_MATRIX_SIN(NAME, T) \
    DEFINE_STRUCT_MATRIX_COS(NAME, T) \
    DEFINE_STRUCT_MATRIX_LOG(NAME, T) \



